/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
#undef Main_serialVersionUID
#define Main_serialVersionUID 1i64
#undef Main_serialVersionUID
#define Main_serialVersionUID 1i64
/*
 * Class:     Main
 * Method:    getEventInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Main_getEventInfo
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
